# Generated by Django 3.1.7 on 2021-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0002_auto_20210811_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(max_length=50),
        ),
    ]
