# Generated by Django 3.1.7 on 2021-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0003_auto_20210811_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
