# Generated by Django 3.1.7 on 2021-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0010_auto_20210811_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
