# Generated by Django 3.1.7 on 2021-08-11 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0012_auto_20210811_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofb',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
