# Generated by Django 3.1.7 on 2021-08-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0013_student_dateofb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dateofb',
            new_name='dateofbirth',
        ),
    ]
